"""Public disclosures match implemented data paths. No compliance promises."""
import html

CONTACT="prathamprateek76@gmail.com"
PRIVACY="""Crayon privacy policy
Last updated: October 9, 2026
Operator and contact: Pratham Prateek Mohanty, prathamprateek76@gmail.com.
Crayon is a Telegram assistant. Use it only if you are comfortable with Telegram, Render, Neon and the AI providers processing the data described here. Do not upload credentials or other secrets.
Groups: exact @crayon_v1_bot mentions and direct commands are answered; untagged conversation is ignored. Public questions use the tagged message only, not private history. Private-action requests first disclose the group audience and require each requester to opt in with enable my group actions. After that, the requester's own requested Gmail/calendar, memory, drafts or task results appear in that group and are visible to all members, not just the requester. Never another member's account. Controls bind requester, chat and displayed draft. No private compose/history continuation crosses chats. Google connection links and proactive monitoring stay in private DM. Tagged action text/results can be stored under the requester's account as ordinary chat; no other member's untagged conversation is stored. Telegram retains group messages under its policies.
WhatsApp test transport: optional allowlisted private-number channel with a separate user identity and no Telegram-memory/Google merge. Signed webhook payloads queue in Neon; duplicate message IDs do not repeat processing. Queued message bodies/profile names are cleared on completion or uncertain processing; transport metadata expires after seven days and delete-data also clears the user's transport rows. Outbound delivery status records hold recipient, wamid, state, timestamp and numeric error code, not provider error prose. No groups, paid template route or out-of-window send.
Ordinary chat: Telegram user ID, display name, chat text, assistant replies, saved facts, notes, reminders, tasks and audit events are stored in Neon Postgres. Chat/history and selected facts are sent to Google's Gemini API to answer you. If the configured free OpenRouter fallback is enabled and Gemini fails, ordinary chat/history/facts and compatible inline images may go to OpenRouter and its selected free-model provider. Routing requires zero-price limits and providers declaring no data collection. Free fallback availability is not guaranteed. The operator of a supplied third-party API key may see usage records in their dashboard; do not assume prompts are invisible to account administrators. Web searches can send your search query to search providers. Data remains until you delete it; /memory and /forget provide controls. /delete_my_data confirm removes stored profile, facts, messages, notes, tasks, reminders and pending actions. Minimal audit/operational records may remain.
Media: files up to 20,000,000 bytes are downloaded in server memory. Photos, PDF, audio and video can be sent to Gemini. Large media and video are temporarily uploaded through Gemini Files API and deletion is attempted after processing. If immediate deletion fails, Google normally auto-deletes after 48 hours. Crayon warns if cleanup cannot be confirmed. Raw files are not saved by Crayon to persistent storage. Up to 3,000 characters of the analysis are retained in chat history for follow-up questions. Telegram keeps the original message under its own policies. Office text is extracted with limits; archives are listed without execution. Unknown formats are acknowledged, not decoded.
Internal work queue: explicitly requested public-source research/page receipts and basic arithmetic can run in the background. Job title, fixed steps, fetched public excerpts, source URLs, progress, errors and completion timestamps are stored in Neon until deletion. No Google data, external writes or account actions enter this queue. Completion delivery respects quiet hours; free hosting and quotas can delay work. Interrupted jobs stop as blocked, not silently retried.
Google connection: optional, per-user OAuth, currently testing mode for named test users. Permissions requested: email identity, read Gmail, read primary-calendar events (optional calendar.events write permission only through enable calendar booking), and send Gmail only after your explicit draft confirmation. Tokens are encrypted with a server-held key in Neon and resolved only by the requesting Telegram user ID. Tokens can expire or be revoked. /disconnect_google revokes Google access and deletes stored credentials, OAuth links and pending drafts. /delete_my_data also disconnects Google. A failed Google revocation is reported and you can remove access in your Google account.
Google data use: direct /gmail, /gmail_read and /calendar commands return requested results to your DM, or the originating group after your own audience opt-in and direct request. Crayon does not pass these mailbox/calendar results to Gemini, AI training or its permanent memory. Requested content is sent to Telegram to show you the result; Telegram retains messages according to its own policy. Email drafts you explicitly enter are encrypted temporarily in Neon with a ten-minute confirmation window; expired pending drafts are cleaned when draft/connection operations run. No email is sent by model instructions, inbox content or scheduled tasks. Uncertain sends are not automatically retried. Multiple To recipients, CC and BCC are shown in the exact confirmation preview. Attachments are not supported by this draft command. A missing real signature name is requested directly from each member and saved encrypted; Telegram display handles are not used as email signatures.
Email watch is opt-in, hourly during awake hours, sender/subject and bounded provider snippet excerpts with bounded cached message IDs/check timestamps in Neon. No body reads or Gemini processing. IMPORTANT/starred labels and subject words guide fallible attention triage. Turning checks off deletes watch state. Calendar previews are encrypted for10minutes and require exact Create approval. Calendar reads and writes are owner-only. Events are private primary-calendar entries, with optional guest emails and popup reminders explicitly listed in each preview. Confirmed guest events request email invitations; solo events send no invitations. No video link is generated. Conflicts are checked before creation and stored event fields are read back. Email delivery to guests is not independently confirmed. No calendar action is triggered by email content. Disconnect removes calendar previews, public-form previews and watch state. Public form beta uses separate deployment-reviewed adapters, exact encrypted ten-minute previews and one-use submission approval. Destination/fields/page are checked again before submitting. No general website coverage, login, purchases or payments. The controlled demo does not make a booking. Form data reaches only the reviewed destination and is not sent to an AI model. Outcomes without confirmation are not automatically retried.
Separate Workspace connection: optional per-member Google OAuth on the Crayon Workspace project, currently testing for named users. It requests verified email identity plus Google Docs and Sheets permissions, separately from Gmail/calendar consent. Tokens are encrypted and bound to the member and provider in Neon. Connection links expire after ten minutes, are one-use, and use PKCE. Requested bounded Docs and Sheets reads are shown only to the requester in private chat, or the originating group after that requester's audience opt-in; these results are not sent to AI models or saved in personal memory. Sheet updates use a displayed preview, exact confirmation and compare-before-write, with readback; values are written as RAW, not formulas. Disconnect workspace attempts Google revocation and removes stored Workspace tokens and pending connection links. Member browser/computer and general credential vault are not generally enabled; they remain blocked until per-member isolation is verified.
Google API data is used only to provide the requested user-facing features, not sold, used for advertising, lending or unrelated purposes. No human review is part of normal Google reads. The operator may investigate limited data for security or bugs as permitted by Google's rules. The Google API connection follows Google's API Services User Data Policy, including Limited Use requirements. Public verification is pending, not certified.
Security: HTTPS is used in transit and Google tokens/drafts have application-level encryption. Other stored chat data uses the database provider's protections. Access controls and heuristic secret detection reduce risk but do not guarantee perfect security. Contact the operator for questions or deletion issues.
Changes: material Google-data-use changes need updated disclosures and consent before new use. No Google-data uses beyond those described here are enabled.
"""
TERMS="""Crayon terms
Crayon is an experimental Telegram assistant operated by Pratham Prateek Mohanty. Contact: prathamprateek76@gmail.com.
Free hosting can sleep or restart; reminders and replies are best-effort, not guaranteed deadlines. Model output can be wrong. Review important facts and all outgoing email content and recipients before confirming. File parsing has format and size limits. Do not rely on Crayon for emergencies.
Do not upload secrets, unlawful content or data you do not have permission to share. Do not use the service to harm others or evade service limits. Google connection is optional and in testing mode, not generally verified. The operator may suspend access for safety or quota reasons. No paid service or billing commitment is included.
You control deletion and Google disconnect through the commands described in the privacy policy. These terms do not waive rights provided by applicable law.
"""

def page(path):
    text=PRIVACY if path=="/privacy" else TERMS
    paras=text.split("\n")
    return '<!doctype html><meta name="viewport" content="width=device-width, initial-scale=1"><title>Crayon '+('privacy' if path=='/privacy' else 'terms')+'</title><main style="max-width:760px;margin:40px auto;padding:20px;font:17px/1.6 sans-serif"><h1>'+html.escape(paras[0])+'</h1>'+''.join('<p>'+html.escape(p)+'</p>' for p in paras[1:] if p)+'<a href="/">Crayon home</a></main>'
