"""Opt-in, Free-plan-only ElevenLabs speech. No paid fallback or cloned voices."""
import os,re
import httpx
import cr_db as db
from cr_safety import looks_like_secret,clean_text

def init():
    db.q('CREATE TABLE IF NOT EXISTS voice_budget(period BIGINT PRIMARY KEY,used INTEGER NOT NULL DEFAULT 0)',fetch='none')
def enabled(uid):return db.kv_get('voice_optin_'+str(uid),False) is True
def synthesize(uid,text):
    if not enabled(uid):raise ValueError('Voice is off. Use /voice on to opt in first.')
    key=os.environ.get('ELEVENLABS_API_KEY','');voice=os.environ.get('ELEVENLABS_VOICE_ID','') or db.kv_get('voice_design_selected','')
    if not key or not re.fullmatch(r'[A-Za-z0-9]{15,40}',voice):raise ValueError('Voice setup is not ready. Device read-aloud is still available on web.')
    text=clean_text(text)
    if not text.strip() or len(text)>1200 or looks_like_secret(text):raise ValueError('Voice accepts 1-1200 characters and no secrets. Shorten the text.')
    with httpx.Client(timeout=45,follow_redirects=False) as client:
        headers={'xi-api-key':key}
        r=client.get('https://api.elevenlabs.io/v1/user/subscription',headers=headers);r.raise_for_status();s=r.json()
        if s.get('tier')!='free' or s.get('can_extend_character_limit') is not False or s.get('allowed_to_extend_character_limit') is not False or s.get('has_open_invoices') is not False or s.get('max_credit_limit_extension',0) not in (0,None):
            raise ValueError('Voice is paused: this account is not verified Free-only with no overage.')
        limit=s.get('character_limit');used=s.get('character_count');period=s.get('next_character_count_reset_unix')
        if not all(isinstance(x,int) and not isinstance(x,bool) for x in (limit,used,period)) or min(limit,used,period)<0 or not period:raise ValueError('Voice quota could not be verified.')
        # Multilingual v2 uses at most the requested one-credit-per-character allowance.
        if used+len(text)>min(limit,10000):raise ValueError('Shared free voice quota reached. No paid call attempted.')
        init()
        row=db.q('INSERT INTO voice_budget(period,used) VALUES(%s,%s) ON CONFLICT(period) DO UPDATE SET used=voice_budget.used+EXCLUDED.used WHERE voice_budget.used+EXCLUDED.used<=10000 RETURNING used',(period,len(text)),'one')
        if not row or row['used']>10000:raise ValueError('Shared 10000-credit voice cap reached.')
        # Keep reservation on failed/uncertain requests. Never retry a generation.
        r=client.post('https://api.elevenlabs.io/v1/text-to-speech/'+voice,headers=headers,params={'output_format':'mp3_44100_128'},json={'text':text,'model_id':'eleven_multilingual_v2','voice_settings':{'stability':0.5,'similarity_boost':0.75}})
        r.raise_for_status()
        if len(r.content)>2000000 or not r.headers.get('content-type','').startswith('audio/'):raise ValueError('Voice response was not a valid bounded audio file.')
        return {'filename':'crayon-elevenlabs.mp3','mime':'audio/mpeg','data':r.content}

def reply_audio(uid,chat,text,meta,out):
    # Fresh consent only. Tool/account results never leave for automatic speech.
    if chat<0 or meta.get('tools') or meta.get('error') or meta.get('confirm'):return False
    try:
        opted=enabled(uid) and db.kv_get('voice_reply_optin_'+str(uid),False) is True
    except Exception:return False
    if not opted:return False
    if len(clean_text(text))>1200:return False
    try:
        out.artifact(chat,synthesize(uid,text))
        out.send(chat,'Voice generated by ElevenLabs. Non-commercial use with attribution.')
        return True
    except Exception:
        out.send(chat,'Voice unavailable or free cap reached. Text is kept; no retry or paid fallback.')
        return False

def handle(uid,chat,text,out):
    if not text.startswith(('/voice','/speak ')):return False
    if chat<0:out.send(chat,'Voice settings and speech are private-DM only.');return True
    if text.strip()=='/voice on':
        db.kv_set('voice_optin_'+str(uid),True)
        db.kv_set('voice_reply_notice_'+str(uid),True)
        out.send(chat,'Explicit /speak is on. Reply /voice confirm to enable automatic voice notes: short general replies and /speak text are sent to ElevenLabs for audio, using our shared 10000-credit free monthly cap. Text stays alongside audio. Tool/account results and replies over1200characters stay text-only. Generated by ElevenLabs for non-commercial use with attribution. /voice off stops voice.');return True
    if text.strip()=='/voice confirm':
        if not enabled(uid) or db.kv_get('voice_reply_notice_'+str(uid),False) is not True:out.send(chat,'Read /voice on first, then confirm.');return True
        db.kv_set('voice_reply_optin_'+str(uid),True)
        out.send(chat,'Automatic short general reply audio enabled. /voice off stops voice. Text remains alongside.');return True
    if text.strip()=='/voice off':db.kv_set('voice_optin_'+str(uid),False);db.kv_set('voice_reply_optin_'+str(uid),False);out.send(chat,'Voice off.');return True
    if not text.startswith('/speak '):out.send(chat,'Voice '+('on' if enabled(uid) else 'off')+'. Use /voice on, /voice off, or /speak text (up to1200characters).');return True
    try:
        item=synthesize(uid,text[7:].strip());out.artifact(chat,item);out.send(chat,'Voice generated by ElevenLabs. Non-commercial use with attribution. Text: '+text[7:].strip())
    except Exception as e:
        # Do not surface provider error details/credentials.
        out.send(chat,str(e) if isinstance(e,ValueError) else 'Voice generation was not confirmed. No automatic retry or paid fallback. Use text or web read-aloud.')
    return True

def setup(action):
    """Admin self-test setup only. Raw keys never returned; design is idempotent."""
    import base64
    key=os.environ.get('ELEVENLABS_API_KEY','')
    if not key:return {'ok':False,'error':'Voice key absent'}
    with httpx.Client(timeout=90,follow_redirects=False) as client:
        headers={'xi-api-key':key}
        r=client.get('https://api.elevenlabs.io/v1/user/subscription',headers=headers)
        if r.status_code!=200:return {'ok':False,'status':r.status_code,'error':'Subscription check failed'}
        s=r.json()
        status={k:s.get(k) for k in ('tier','character_count','character_limit','next_character_count_reset_unix','voice_slots_used','voice_limit','can_extend_character_limit','allowed_to_extend_character_limit','has_open_invoices')}
        if action=='status':return {'ok':True,'subscription':status}
        if s.get('tier')!='free' or s.get('has_open_invoices') is not False or s.get('can_extend_character_limit') is not False or s.get('allowed_to_extend_character_limit') is not False:return {'ok':False,'error':'Free-only subscription required','subscription':status}
        if action=='premade_list':
            r=client.get('https://api.elevenlabs.io/v1/voices',headers=headers)
            if r.status_code!=200:return {'ok':False,'status':r.status_code,'error':'Premade voice read failed'}
            voices=[{k:v.get(k) for k in ('voice_id','name','category','labels','preview_url','description')} for v in r.json().get('voices',[]) if v.get('category')=='premade']
            db.kv_set('voice_premade_candidates',voices)
            return {'ok':True,'voices':voices}
        if action.startswith('premade_test:'):
            index=int(action.split(':')[1]);voices=db.kv_get('voice_premade_candidates',[])
            if not 0<=index<len(voices):return {'ok':False,'error':'Invalid premade candidate'}
            row=db.q("INSERT INTO kv(key,value) VALUES('voice_premade_test_claim','true'::jsonb) ON CONFLICT DO NOTHING RETURNING key",fetch='one')
            if not row:return db.kv_get('voice_premade_test_result',{'ok':False,'error':'Test already requested; inspect before retry'})
            text="Hello, I'm Crayon. Namaste! Let's work on your next idea together."
            if s.get('character_count',10000)+len(text)>min(s.get('character_limit',0),10000):return {'ok':False,'error':'Insufficient free quota'}
            init();period=s['next_character_count_reset_unix']
            reserved=db.q('INSERT INTO voice_budget(period,used) VALUES(%s,%s) ON CONFLICT(period) DO UPDATE SET used=voice_budget.used+EXCLUDED.used WHERE voice_budget.used+EXCLUDED.used<=10000 RETURNING used',(period,len(text)),'one')
            if not reserved:return {'ok':False,'error':'Shared cap reached'}
            ident=voices[index]['voice_id']
            r=client.post('https://api.elevenlabs.io/v1/text-to-speech/'+ident,headers=headers,params={'output_format':'mp3_44100_128'},json={'text':text,'model_id':'eleven_multilingual_v2'})
            if r.status_code!=200:
                try:detail=r.json().get('detail',{});code=detail.get('status','unknown') if isinstance(detail,dict) else 'unknown'
                except Exception:code='unknown'
                result={'ok':False,'status':r.status_code,'provider_error_code':code,'error':'Premade TTS failed; no automatic retry'}
            else:
                result={'ok':True,'audio_base_64':base64.b64encode(r.content).decode(),'voice_id':ident,'name':voices[index]['name'],'attribution':'Generated by ElevenLabs. Non-commercial use with attribution.'}
                db.kv_set('voice_design_selected',ident)
            db.kv_set('voice_premade_test_result',result)
            return result
        if action=='library_list':
            r=client.get('https://api.elevenlabs.io/v1/shared-voices',headers=headers,params={'page_size':10,'gender':'female','language':'hi','include_custom_rates':'false'})
            if r.status_code!=200:return {'ok':False,'status':r.status_code,'error':'Library read failed'}
            fields=('voice_id','name','accent','gender','language','description','free_users_allowed','rate','preview_url','verified_languages')
            voices=[{k:v.get(k) for k in fields} for v in r.json().get('voices',[])]
            db.kv_set('voice_library_candidates',voices)
            return {'ok':True,'voices':voices}
        if action.startswith('library_test:'):
            index=int(action.split(':')[1]);voices=db.kv_get('voice_library_candidates',[])
            if not 0<=index<len(voices):return {'ok':False,'error':'Invalid library candidate'}
            row=db.q("INSERT INTO kv(key,value) VALUES('voice_library_test_claim','true'::jsonb) ON CONFLICT DO NOTHING RETURNING key",fetch='one')
            if not row:return db.kv_get('voice_library_test_result',{'ok':False,'error':'Test already requested; inspect before retry'})
            text='Hello, namaste.'
            if s.get('character_count',10000)+len(text)>min(s.get('character_limit',0),10000):return {'ok':False,'error':'Insufficient free quota'}
            init();period=s['next_character_count_reset_unix']
            reserved=db.q('INSERT INTO voice_budget(period,used) VALUES(%s,%s) ON CONFLICT(period) DO UPDATE SET used=voice_budget.used+EXCLUDED.used WHERE voice_budget.used+EXCLUDED.used<=10000 RETURNING used',(period,len(text)),'one')
            if not reserved:return {'ok':False,'error':'Shared cap reached'}
            ident=voices[index]['voice_id']
            r=client.post('https://api.elevenlabs.io/v1/text-to-speech/'+ident,headers=headers,params={'output_format':'mp3_44100_128'},json={'text':text,'model_id':'eleven_multilingual_v2'})
            if r.status_code!=200:
                try:detail=r.json().get('detail',{});code=detail.get('status','unknown') if isinstance(detail,dict) else 'unknown'
                except Exception:code='unknown'
                result={'ok':False,'status':r.status_code,'provider_error_code':code,'error':'Library TTS failed; no automatic retry'}
            else:
                result={'ok':True,'audio_base_64':base64.b64encode(r.content).decode(),'voice_id':ident,'name':voices[index]['name'],'attribution':'Generated by ElevenLabs. Non-commercial use with attribution.'}
                db.kv_set('voice_design_selected',ident)
            db.kv_set('voice_library_test_result',result)
            return result
        if action=='design_retry_permission':
            failed=db.kv_get('voice_design_failure',None)
            if not failed or failed.get('status')!=403 or db.kv_get('voice_design_previews',None):return {'ok':False,'error':'No confirmed permission failure eligible for retry.'}
            db.q("DELETE FROM kv WHERE key='voice_design_claim'",fetch='none')
            action='design'
        if action=='design':
            saved=db.kv_get('voice_design_previews',None)
            if saved:return {'ok':True,'cached':True,'previews':saved}
            row=db.q("INSERT INTO kv(key,value) VALUES('voice_design_claim','true'::jsonb) ON CONFLICT DO NOTHING RETURNING key",fetch='one')
            if not row:return {'ok':False,'error':'Design already requested; inspect before retry'}
            text="Hi, I'm Crayon. Let's turn your next idea into something real. We can study together, explore a question, or make a clear plan. Chalo, shuru karte hain."
            if s.get('character_count',10000)+len(text)>min(s.get('character_limit',0),10000):return {'ok':False,'error':'Insufficient free quota'}
            init();period=s['next_character_count_reset_unix']
            row=db.q('INSERT INTO voice_budget(period,used) VALUES(%s,%s) ON CONFLICT(period) DO UPDATE SET used=voice_budget.used+EXCLUDED.used WHERE voice_budget.used+EXCLUDED.used<=10000 RETURNING used',(period,len(text)),'one')
            if not row:return {'ok':False,'error':'Shared cap reached'}
            r=client.post('https://api.elevenlabs.io/v1/text-to-voice/design',headers=headers,params={'output_format':'mp3_44100_128'},json={'voice_description':'An adult female voice from India. Natural Hindi-influenced Indian English, fluent clear English and Hindi. Smart, warm, calm, conversational and confident. No exaggerated accent. Clear articulation with gentle energy, like a helpful study companion.','text':text,'model_id':'eleven_multilingual_ttv_v2','auto_generate_text':False})
            if r.status_code!=200:
                try:detail=r.json().get('detail',{});code=detail.get('status','unknown') if isinstance(detail,dict) else 'unknown'
                except Exception:code='unknown'
                code=code if re.fullmatch(r'[A-Za-z0-9_-]{1,80}',str(code)) else 'unknown'
                failure={'ok':False,'status':r.status_code,'provider_error_code':code,'error':'Design failed; no automatic retry'}
                db.kv_set('voice_design_failure',failure)
                return failure
            previews=r.json().get('previews',[])[:3]
            db.kv_set('voice_design_previews',previews)
            return {'ok':True,'previews':previews,'attribution':'Generated by ElevenLabs. Non-commercial use with attribution.'}
        if action.startswith('select:'):
            index=int(action.split(':')[1]);previews=db.kv_get('voice_design_previews',[])
            if not 0<=index<len(previews):return {'ok':False,'error':'Invalid preview'}
            saved=db.kv_get('voice_design_selected',None)
            if saved:return {'ok':True,'voice_id':saved,'cached':True}
            claim=db.q("INSERT INTO kv(key,value) VALUES('voice_design_select_claim','true'::jsonb) ON CONFLICT DO NOTHING RETURNING key",fetch='one')
            if not claim:return {'ok':False,'error':'Voice save previously requested. Inspect provider state before retry.'}
            r=client.post('https://api.elevenlabs.io/v1/text-to-voice',headers=headers,json={'voice_name':'Crayon Indian companion','voice_description':'Female Indian Hindi-English study companion','generated_voice_id':previews[index]['generated_voice_id']})
            if r.status_code!=200:return {'ok':False,'status':r.status_code,'error':'Voice save not confirmed'}
            ident=r.json()['voice_id'];db.kv_set('voice_design_selected',ident);return {'ok':True,'voice_id':ident}
        return {'ok':False,'error':'Unknown voice setup action'}
