"""Opt-in, Free-plan-only ElevenLabs speech. No paid fallback or cloned voices."""
import os,re
import httpx
import cr_db as db
from cr_safety import looks_like_secret,clean_text

def init():
    db.q('CREATE TABLE IF NOT EXISTS voice_budget(period BIGINT PRIMARY KEY,used INTEGER NOT NULL DEFAULT 0)',fetch='none')
def enabled(uid):return db.kv_get('voice_optin_'+str(uid),False) is True
def synthesize(uid,text):
    if not enabled(uid):raise ValueError('Voice is off. Use /voice on to opt in first.')
    key=os.environ.get('ELEVENLABS_API_KEY','');voice=os.environ.get('ELEVENLABS_VOICE_ID','')
    if not key or not re.fullmatch(r'[A-Za-z0-9]{15,40}',voice):raise ValueError('Voice setup is not ready. Device read-aloud is still available on web.')
    text=clean_text(text)
    if not text.strip() or len(text)>1200 or looks_like_secret(text):raise ValueError('Voice accepts 1-1200 characters and no secrets. Shorten the text.')
    with httpx.Client(timeout=45,follow_redirects=False) as client:
        headers={'xi-api-key':key}
        r=client.get('https://api.elevenlabs.io/v1/user/subscription',headers=headers);r.raise_for_status();s=r.json()
        if s.get('tier')!='free' or s.get('can_extend_character_limit') is not False or s.get('allowed_to_extend_character_limit') is not False or s.get('has_open_invoices') is not False or s.get('max_credit_limit_extension',0) not in (0,None):
            raise ValueError('Voice is paused: this account is not verified Free-only with no overage.')
        limit=s.get('character_limit');used=s.get('character_count');period=s.get('next_character_count_reset_unix')
        if not all(isinstance(x,int) and not isinstance(x,bool) for x in (limit,used,period)) or min(limit,used,period)<0 or not period:raise ValueError('Voice quota could not be verified.')
        # Multilingual v2 uses at most the requested one-credit-per-character allowance.
        if used+len(text)>min(limit,10000):raise ValueError('Shared free voice quota reached. No paid call attempted.')
        init()
        row=db.q('INSERT INTO voice_budget(period,used) VALUES(%s,%s) ON CONFLICT(period) DO UPDATE SET used=voice_budget.used+EXCLUDED.used WHERE voice_budget.used+EXCLUDED.used<=10000 RETURNING used',(period,len(text)),'one')
        if not row or row['used']>10000:raise ValueError('Shared 10000-credit voice cap reached.')
        # Keep reservation on failed/uncertain requests. Never retry a generation.
        r=client.post('https://api.elevenlabs.io/v1/text-to-speech/'+voice,headers=headers,params={'output_format':'mp3_44100_128'},json={'text':text,'model_id':'eleven_multilingual_v2','voice_settings':{'stability':0.5,'similarity_boost':0.75}})
        r.raise_for_status()
        if len(r.content)>2000000 or not r.headers.get('content-type','').startswith('audio/'):raise ValueError('Voice response was not a valid bounded audio file.')
        return {'filename':'crayon-elevenlabs.mp3','mime':'audio/mpeg','data':r.content}

def handle(uid,chat,text,out):
    if not text.startswith(('/voice','/speak ')):return False
    if chat<0:out.send(chat,'Voice settings and speech are private-DM only.');return True
    if text.strip()=='/voice on':
        db.kv_set('voice_optin_'+str(uid),True)
        out.send(chat,'Voice opted in. /speak text sends that text to ElevenLabs and uses our shared monthly free quota. Generated audio is non-commercial and attributed to ElevenLabs. Auto voice replies remain off. /voice off stops voice.');return True
    if text.strip()=='/voice off':db.kv_set('voice_optin_'+str(uid),False);out.send(chat,'Voice off.');return True
    if not text.startswith('/speak '):out.send(chat,'Voice '+('on' if enabled(uid) else 'off')+'. Use /voice on, /voice off, or /speak text (up to1200characters).');return True
    try:
        item=synthesize(uid,text[7:].strip());out.artifact(chat,item);out.send(chat,'Voice generated by ElevenLabs. Non-commercial use with attribution. Text: '+text[7:].strip())
    except Exception as e:
        # Do not surface provider error details/credentials.
        out.send(chat,str(e) if isinstance(e,ValueError) else 'Voice generation was not confirmed. No automatic retry or paid fallback. Use text or web read-aloud.')
    return True
